# Generated by Django 3.1.6 on 2021-02-17 23:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('state', models.IntegerField(choices=[(0, 'Standing'), (1, 'Withdrawn')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('vote_type', models.IntegerField(choices=[(0, 'First past the post'), (1, 'Approval vote'), (2, 'Single Transferable Vote')], default=0)),
                ('max_votes', models.IntegerField(default=2, help_text='Ignored except in Plurality. Number of candidates selectable per vote')),
                ('seats', models.IntegerField(default=1, help_text='Ignored except in STV. Number of people who can win')),
                ('open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='STVPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.candidate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='STVVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.election')),
                ('selection', models.ManyToManyField(through='votes.STVPreference', to='votes.Candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='STVResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_log', models.TextField()),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votes.election')),
                ('winners', models.ManyToManyField(to='votes.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='stvpreference',
            name='stvvote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.stvvote'),
        ),
        migrations.CreateModel(
            name='FPTPVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.election')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.election'),
        ),
        migrations.CreateModel(
            name='APRVVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.election')),
                ('selection', models.ManyToManyField(to='votes.Candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('spent', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.election')),
            ],
            options={
                'unique_together': {('member', 'election')},
            },
        ),
    ]
