# Generated by Django 3.1.6 on 2021-03-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ('id',)},
        ),
    ]
