# Generated by Django 3.1.6 on 2021-03-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20210305_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
